version: "3.3"
services:
  # n8n:
  #   image: n8nio/n8n
  #   volumes:
  #     - "${HOME}/.n8n:/home/node/.n8n"
  #     # Uncomment following line if you have simlinks from /home/node/.n8n to your repos location. Ensure you correctly setup REPOS_PATH env variable.
  #     #- "${HOME}${REPOS_PATH}:/home/node${REPOS_PATH}"
  #   networks:
  #     - n8n-embed
  #   restart: unless-stopped
  #   environment:
  #     # - N8N_PROTOCOL=http
  #     # - N8N_HOST=127.0.0.1
  #     # - N8N_PORT=5678
  #     - N8N_PATH=/n8n/
  #     # - N8N_EDITOR_BASE_URL=http://127.0.0.1:8080/n8n/
  #     # - VUE_APP_URL_BASE_API=http://127.0.0.1:8080/n8n/
  #     - WEBHOOK_URL=http://127.0.0.1:8080/n8n/
  #     - N8N_SMTP_HOST
  #     - N8N_SMTP_PORT
  #     - N8N_SMTP_USER
  #     - N8N_SMTP_PASS

  # app:
  #   build: app
  #   volumes:
  #     - ./app/index.html:/app/index.html
  #   networks:
  #     - n8n-embed

  web:
    image: nginx
    network_mode: host
    # networks:
    #   - n8n-embed
    volumes:
      - ./nginx-templates:/etc/nginx/templates
    # ports:
    #   - "8080:80"
    environment:
      - NGINX_HOST=127.0.0.1
      - NGINX_PORT=80

networks:
  n8n-embed:
