version: "3.3"
services:
  n8n:
    image: n8nio/n8n
    container_name: n8nthemes-n8n
    # networks:
    #   - n8n-theme-editor
    volumes:
      - n8n:/home/node
      # - "${HOME}/.n8n:/home/node/.n8n"
    environment:
      - N8N_PORT=${N8NTHEMES_PORT_N8N:-5678}
      - N8N_PATH=/n8n/
      # - WEBHOOK_URL=http://127.0.0.1:8080/n8n/

  editor:
    build: .
    image: n8n-theme-editor:latest
    container_name: n8nthemes-editor
    # networks:
    #   - n8n-theme-editor
    environment:
      - PORT=${N8NTHEMES_PORT_EDITOR:-3000}

  nginx:
    image: nginx
    container_name: n8nthemes-nginx
    # networks:
    #   - n8n-theme-editor
    volumes:
      - ./nginx-templates:/etc/nginx/templates
    environment:
      - NGINX_PORT=${N8NTHEMES_PORT_NGINX:-80}
      - N8NTHEMES_N8N_URL=${N8NTHEMES_N8N_URL:-http://n8n:5678/}
      - N8NTHEMES_EDITOR_URL=${N8NTHEMES_EDITOR_URL:-http://editor:3000/}
    ports:
      - ${N8NTHEMES_PORT_NGINX:-80}:${N8NTHEMES_PORT_NGINX:-80}

# networks:
#   n8n-theme-editor:

volumes:
  n8n:
    name: n8nthemes-n8n
