version: "3.3"
services:
  n8n:
    extends:
      file: common.yaml
      service: n8n
    volumes:
      - n8n:/home/node
    networks:
      - n8n-theme-editor
    ports:
      - 5678:5678

  app:
    extends:
      file: common.yaml
      service: app
    networks:
      - n8n-theme-editor
    ports:
      - 3000:80

  nginx:
    extends:
      file: common.yaml
      service: nginx
    depends_on:
      - n8n
      - app
    ports:
      - 80:80
    networks:
      - n8n-theme-editor

volumes:
  n8n:

networks:
  n8n-theme-editor:
