version: "3.3"
services:
  app:
    extends:
      file: common.yaml
      service: app
    network_mode: host
    ports:
      - 3000:80

  nginx:
    extends:
      file: common.yaml
      service: nginx
    network_mode: host
    # ports:
    #   - 80:80
